const text = {
  ca: {
    firstName: 'Nom',
    lastName: 'Cognom',
    bday: 'Aniversari',
    mob: 'Movìl',
    gender: 'Sexe',
    male: 'Home',
    female: 'Dona',
    back: 'Enrere',
    streetName: 'Carrer',
    streetNumber: 'Numero',
    pCode: 'Còdigo Postal',
    city: 'Poble',
    update: 'Actualizar Perfìl',
  },
  es: {
    firstName: 'Nombre',
    lastName: 'Apellido',
    bday: 'Cumpleaños',
    mob: 'Movìl',
    gender: 'Sexo',
    male: 'Hombre',
    female: 'Mujer',
    back: 'Atras',
    streetName: 'Calle',
    streetNumber: 'Numero',
    pCode: 'Còdigo Postal',
    city: 'Pueblo',
    update: 'Actualizar Perfìl',
  },
  en: {
    firstName: 'first Name',
    lastName: 'Last Name',
    bday: 'Birthday',
    mob: 'Mobile',
    gender: 'Gender',
    male: 'Male',
    female: 'Female',
    back: 'Go Back',
    streetName: 'Street',
    streetNumber: 'Number',
    pCode: 'Postal Code',
    city: 'city',
    update: 'Update Profile',
  },
};

export default text;
