const text = {
  ca: {
    title: 'Estem de Guàrdia',
    MONTHS: [
      'Gener',
      'Febrer',
      'Març',
      'Abril',
      'Maig',
      'Juny',
      'Juliol',
      'Agost',
      'Septembre',
      'Octubre',
      'Novembre',
      'Dicembre',
    ],
    WEEKDAYS_LONG: [
      'Diumenge',
      'Dilluns',
      'Dimarts',
      'Dimecres',
      'Dijous',
      'Divendres',
      'Dissabte',
    ],
    WEEKDAYS_SHORT: ['Di', 'Dl', 'Dm', 'Dm', 'Dj', 'Dv', 'Ds'],
  },
  es: {
    title: 'Estamos de Guardia',
    MONTHS: [
      'Enero',
      'Febrero',
      'Marzo',
      'Abril',
      'Mayo',
      'Junio',
      'Julio',
      'Agosto',
      'Septiembre',
      'Octubre',
      'Noviembre',
      'Diciembre',
    ],
    WEEKDAYS_LONG: [
      'Domingo',
      'Lunes',
      'Martes',
      'Miércoles',
      'Jueves',
      'Viernes',
      'Sábado',
    ],
    WEEKDAYS_SHORT: ['Do', 'Lu', 'Ma', 'Mi', 'Ju', 'Vi', 'Sa'],
  },
  en: {
    title: 'We are on Guard',
    MONTHS: [
      'january',
      'February',
      'March',
      'April',
      'May',
      'June',
      'July',
      'August',
      'September',
      'Octuber',
      'November',
      'December',
    ],
    WEEKDAYS_LONG: [
      'Sunday',
      'Monday',
      'Tuesday',
      'Wednesday',
      'Thursday',
      'Friday',
      'Saturday',
    ],
    WEEKDAYS_SHORT: ['Su', 'Mo', 'Tu', 'We', 'Th', 'Fr', 'Sa'],
  },
};

export default text;
