const text = {
  ca: {
    back: 'Enrere',
    id: 'DNI/ NIE',
    CIP: 'CIP',
    bday: 'Aniversari',
    gender: 'Sexe',
    tel: 'fixe',
    mob: 'Mòvil',
    email: 'Email',
    address: 'Direcciò',
    editPhoto: 'Canvia Foto',
    editProfile: 'Canvia Perfìl',
    editPhotoText: 'Sisplau, Escull el seu now foto de perfìl:',
  },
  es: {
    back: 'Atras',
    id: 'DNI/ NIE',
    CIP: 'CIP',
    bday: 'Cumpleaños',
    gender: 'Sexo',
    tel: 'fijo',
    mob: 'Movil',
    email: 'Email',
    address: 'Dirección',
    editPhoto: 'Cambiar Foto',
    editProfile: 'Cambiar Perfil',
    editPhotoText: 'Por favor, seleciona su nuevo foto de peril:',
  },
  en: {
    back: 'Go Back',
    id: 'National ID',
    CIP: 'Social Security Nº',
    bday: 'Birthday',
    gender: 'Gender',
    tel: 'Telephone',
    mob: 'Mobile',
    email: 'Email',
    address: 'Address',
    editPhoto: 'Edit Photo',
    editProfile: 'Edit Profile',
    editPhotoText: 'Please, Select your new  profile image:',
  },
};

export default text;
