const text = {
  ca: {
    back: 'Enrere',
    id: 'DNI/ NIE',
    CIP: 'CIP',
    bday: 'Aniversari',
    gender: 'Sexe',
    tel: 'fixe',
    mob: 'Mòbil',
    email: 'Mail',
    address: 'Direcció',
    editPhoto: 'Canvia la fotografia',
    editProfile: 'Canvia Perfil',
    editPhotoText: 'Si us plau, escull la teva nova fotografia de perfil:',
    contestText: 'Si us plau, escull la fotografia:',
  },
  es: {
    back: 'Atrás',
    id: 'DNI/ NIE',
    CIP: 'CIP',
    bday: 'Cumpleaños',
    gender: 'Sexo',
    tel: 'fijo',
    mob: 'Movil',
    email: 'Email',
    address: 'Dirección',
    editPhoto: 'Cambiar Foto',
    editProfile: 'Cambiar perfil',
    editPhotoText: 'Por favor, selecciona tu nueva foto de perfil:',
    contestText: 'Por favor, selecciona tu foto:',
  },
  en: {
    back: 'Go Back',
    id: 'National ID',
    CIP: 'Social Security Nº',
    bday: 'Birthday',
    gender: 'Gender',
    tel: 'Telephone',
    mob: 'Mobile',
    email: 'Email',
    address: 'Address',
    editPhoto: 'Edit Photo',
    editProfile: 'Edit Profile',
    editPhotoText: 'Please, Select your new  profile image:',
    contestText: 'Please, Select your image:',
  },
};

export default text;
